---
development:
  cloud_name: coder-factory
  api_key: '767274749816166'
  api_secret: CRN-Tcdy6YyibdHh06yzaDAemMU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: coder-factory
  api_key: '767274749816166'
  api_secret: CRN-Tcdy6YyibdHh06yzaDAemMU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: coder-factory
  api_key: '767274749816166'
  api_secret: CRN-Tcdy6YyibdHh06yzaDAemMU
  enhance_image_tag: true
  static_image_support: false
